# Generated by Django 5.2.17 on 2026-09-03 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_managedcommunityprojection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedcommunityprojection",
            name="technical_email",
        ),
    ]
