# Generated by Django 5.2.17 on 2026-09-02 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_album_core_catalog_ref_and_more'),
        ('journal', '0020_collectionitem'),
        ('mastodon', '0003_managedvinylhubcommunityaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCommunityPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation_key', models.CharField(max_length=255)),
                ('source_piece_uid', models.UUIDField(blank=True, editable=False, null=True)),
                ('outbound_intent', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('unknown', 'Unknown'), ('remote_missing', 'Remote missing')], default='pending', max_length=24)),
                ('remote_status_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('remote_status_url', models.URLField(blank=True, max_length=2048)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_category', models.CharField(blank=True, max_length=40)),
                ('last_error_text', models.CharField(blank=True, max_length=500)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_community_publications', to='catalog.item')),
                ('managed_social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_community_publications', to='mastodon.socialaccount')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_community_publications', to='journal.piece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_community_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'state'], name='managed_pub_user_state'), models.Index(fields=['state', 'updated_at'], name='managed_pub_state_updated')],
                'constraints': [models.UniqueConstraint(fields=('managed_social_account', 'operation_key'), name='managed_pub_account_operation_key'), models.UniqueConstraint(condition=models.Q(('remote_status_id__isnull', False)), fields=('managed_social_account', 'remote_status_id'), name='managed_pub_account_remote_status')],
            },
        ),
    ]
